### ISSUE TITLE
Hackaton suggestion

### ISSUE THREAD

**Issue by SolalPirelli** [HackEPFL/events#12]
Hi guys,

Are you still open to organizing hackatons?

I'm a Microsoft Student Partner, and Microsoft Switzerland is interested in doing a student hackaton at EPFL next semester. Since your association has experience in doing these things (and I can testify you do them well :) ), we thought you'd be great partners for that.

The goal is to let students run wild with ideas, while encouraging them to use some MS techs like Azure for hosting. We haven't fully settled on the exact format yet, though, so we're open to suggestions.

(cc: @Mandur aka Mikhail Chatillon, MS Technical Evangelist and MSP boss; @SebastienAndreina, other MSP at EPFL; @acknowledge aka Jacky Casas, MSP in Fribourg)

**Comment by romac** [comment]
Hey Solal,

Sorry for the late reply, Jérémy just reminded me about your inquiry.

We are currently in the process of shutting down HackEPFL, which means that we won't officially take part in the hackathon, but are nonetheless happy to answer any questions you guys might have :) We can always grab a beer together sometime early next year to discuss all that if you like. In the meantime, you can take a look at https://github.com/HackEPFL/events/issues/11 to get an idea of the costs involved regarding the meals, etc.
