### ISSUE TITLE
Estimate costs for meals during the Facebook Hackathon

### ISSUE THREAD

**Issue by pirroh** [HackEPFL/events#2]
We need to get estimates for food during the Facebook Hackathon. We expect around 50 people, and we need to cover:
- lunch and dinner on Saturday
- breakfast and lunch on Sunday
- plenty of snacks, coffee, juices, Red Bull, etc.

Here's our tentative plan:
- pizza on Saturday from http://leskipper.ch
- dinner on Saturday from http://chinadomicile.ch/
- lunch on Sunday from http://www.saveursdailleurs.ch/

We're still missing a place where to get coffee + pastries on Sunday morning.

@BinaryBrain: could you take care of this? We need a French speaker who knows well the Lausanne area, and is used to organizing events :)

**Comment by romac** [comment]
Just did a quick estimation for the costs:

|  Date |  Meal | People | Final cost | Status | Delivery | Payment |
| --- | --- | --- | --: | --- | --- | --- |
| **Saturday** lunch | Pizzas | 60 | CHF 936.00 | Confirmed | 1:00pm | Credit card |
| **Saturday** evening | Chinese | 50 | CHF 1355.00 | Confirmed | 8:00pm | Credit card |
| **Sunday** morning | Croissants | 50 | CHF 195.00 | Confirmed | 8:00am | Bill |
| **Sunday** lunch | Thai | 50 | CHF 1200.00 | [Confirmed](http://cl.ly/253L310D1k0q) | 1:00pm | Credit card at shop |
| **Whole weekend** | Drinks | 50 | CHF 500.00 |  |  |  |
|  |  | **Total** | **CHF 4206.-** |  |  |  |

**Comment by BinaryBrain** [comment]
@pirroh I may find something cool.
@romac 40.- CHF / pers. for drinks? Isn't it a bit overrated? If everybody drinks 3 litters of Coke (1/2 6-pack), it's about 7.- CHF / pers.
And for pizzas, maybe we can deal something with La Roulotte, can't we?

**Comment by romac** [comment]
@BinaryBrain: Now that you say it, it seems a bit overrated :P 10-15.- per person should definitely be enough. I think the most expensive drinks are the Red Bulls but we can also buy another cheaper brand. I reflected that in the above table.

**Comment by pirroh** [comment]
Good news everyone! The budget we have in mind has been approved by Facebook, so we should go ahead and inform all the catering companies.
@BinaryBrain @romac: could you guys take care of it?

We still need a solution for Sunday morning. Any ideas?

**Comment by romac** [comment]
Alright, so I ordered the menu for Saturday evening at China Domicile.
- CHF 25.50 per person.
- Delivery around 7pm.
- We can call them Thursday or Friday morning to tell them the exact number of meals we need.
- We can pay with a credit card when they come to get their stuff back.
- They'll deliver "bain-maries", and, for an additional CHF 60-80.-, they can also bring plates, forks, etc.

I still have to send them an e-mail with the address of delivery + map, as well as the name to put on the invoice (@pirroh: can you check that with Facebook?).

**Comment by pirroh** [comment]
We can put Ruth McIntyre on the invoice. She will pay by credit card on delivery.
+1 to get also plates/forks.

**Comment by romac** [comment]
@pirroh: Alright! What about the address of delivery? The parking at Ch. Alan Turing between BC and MXH looks like the best spot.

**Comment by romac** [comment]
I just ordered the menu for Sunday lunch at Saveur d'Ailleurs.
- CHF 24.00 per person.
- Delivery around 12pm.
- We can call them Friday morning to tell them the exact number of meals we need.
- They'll also deliver "bain-maries" or something like that, along with paper plates, and biodegradable forks/knives.

@pirroh: There's one issue: we can't pay them by credit card on delivery. But
a) They can make an invoice, and we (Ruth) will pay them by bank transfer (if that's an option for Ruth).
b) We can go to the restaurant and pay there with a credit card. But the restaurant is located at Ouchy…

**Comment by pirroh** [comment]
The parking at Ch. Alan Turing is the best place, I agree (also the Facebook ppl are parking there).
For the payment of "Saveur d'Ailleurs" let's go with option b) for now, and then we'll discuss about it with Ruth on Saturday (in general, let's try to use the credit card as much as possible).

**Comment by romac** [comment]
Called Le Skipper but they don't do delivery. Should I then order the pizzas at a shop like PizzaFly? That'll most likely cost us something like 20.- per person, if they can handle it.

**Comment by pirroh** [comment]
Ok for PizzaFly: we can save money buying only the 40cm pizzas, and we're sure that we won't have problems if we can't find a car.
Now I guess the car will be useful only for the drinks...

**Comment by romac** [comment]
@pirroh: Called Fleur de Pains for Sunday morning breakfast, and they can deliver croissants + chocolate breads(?). 
Should cost us 250.- or something like that, will ask for an estimation today.
But they ask for a billing address. Can you check with Ruth if that's OK for her, and if so, what should the address be?

**Comment by BinaryBrain** [comment]
Hi guys,
Sorry I had a lot of work.
Everything's all right?

**Comment by romac** [comment]
@pirroh: Should I then order something like 20 40cm pizzas?

**Comment by romac** [comment]
@BinaryBrain: No problem, I'm taking care of it :)

**Comment by pirroh** [comment]
@romac: breakfast from Fleur de Pains sounds perfect. Do we get also hot coffee?
For the billing address, I already asked Sandra@FB about it, and will let you know soon.
In general, we gotta be sure they want the address only for legal reasons, and NOT to send invoices to them! (because we're only paying by credit card).

w.r.t. pizzas, 20 x 40cm pizzas is perfect!

**Comment by romac** [comment]
@pirroh: Alright, but the issue is that two suppliers don't have a credit card reader, therefore we'll have to go the restaurant (Saveur d'Ailleurs) to pay for Sunday's lunch, and I'll ask if that's also possible for Fleur de Pains. I'll keep you posted. 

Another solution would be that we pay ourselves the invoice from Fleur de Pains and then ask FB to refund us (I seem to recall that it was a possibility?)

**Comment by pirroh** [comment]
Yes it's a possibility, but it requires paperwork from both sides and at least 30 days to get the refund. So, if it does not become a blocker, let's avoid it ;)

**Comment by romac** [comment]
@pirroh: Problem, Fleur de Pains doesn't accept payment by credit card at all (neither on delivery nor at the shop itself), so the only way to pay them is via invoice. Since it's not very expensive (CHF 195.-), I think one of us can pay it and then, yeah we'll have to ask Facebook for a refund…
