### ISSUE TITLE
Organize Drinkup #2

### ISSUE THREAD

**Issue by romac** [HackEPFL/events#3]
Let's organize our 2nd [drinkup](http://hackersatepfl.com/events/drinkup-1)!
- [x] Settle on a date (maybe sometime in December after the midterms).
- [x] Find a sponsor to pay for the drinks.
- [x] Create the Facebook event.
- [ ] Advertise the event on the newsletter.

**Comment by FredericJacobs** [comment]
W00t :) Sounds awesome. I will ping @pirroh too.

**Comment by romac** [comment]
Alright, so drinkup #2 will be part of [this talk](http://hackersatepfl.com/events/%22randomness-in-crypto%22-followed-by-a-h@epfl-drink-up/).
