### ISSUE TITLE
Meet with Hack4Good

### ISSUE THREAD

**Issue by dtsbourg** [HackEPFL/events#5]
@romac and I are going to meet them now, will post digest of our exchange here.

**Comment by FredericJacobs** [comment]
So?

**Comment by dtsbourg** [comment]
Sorry thought you saw the mail. Here's a copy:

Salut Dylan, Romain & co,

Thank you for taking the time to meet. See below key facts discussed about it.

Looking forward to the organization of the Hack4Good! 

I have put a lit of potential sponsors to reach, a few already contacted after our meeting:
WWF
IUCN
UNEP, UNCTAD, UNWFP
OECD
Impact Hub Zurich
Arduino
EPFL Cooperation
EPFL Industry Relations Officer, Aurélie Schick
EPFL Innogrants, Hervé Lebret.

As mentioned last minute, Luca & me will put together a list of online databases & tools to use for the hackathon.

Cheers,
Jonathan

Name: Hack4Good

Theme: Climate change, environmental protection and social development

Objective: build a website / app / hack to prevent climate change, help environmental protection and social development

Team: Romain, Dylan, Luca, Jonathan, Frederic?
Partners for organization: GNU, Vivapoly, Goodwall, a few lady friends

Date: 
November 8/9 with sponsors (October 20 deadline)
December 6/7 if sponsors not found beginning of October

Place: Bibliothèque INM

Poster: EPFL / HES (Yverdon) / UNIL 

Winning prices: To be decided with sponsors

Budget: EUR 5k to EUR 10k

Jury & Presentation: 1 of Hackers @ EPFL, 1 of Mikro Trees, 1 or 2 of Sponsors

Event organization:
Hashtag to create for people to post & share their ideas.
Idea could be to start the presentation engaging them with global issues the crowd can think about.
No junk food. No snacks. No soda. Vegetables & fruits. Water. Tea.
Teams of 2 to 5

To-do list for now:
Sponsors to reach => Jonathan
Poster => Dylan / Frederic
Online databases & tools => Luca

**Comment by FredericJacobs** [comment]
Cool. So it's happening.

**Comment by romac** [comment]
See #8
