### ISSUE TITLE
Rust Workshop - Teaching resources

### ISSUE THREAD

**Issue by romac** [HackEPFL/events#9]
**Teaching:**
- https://github.com/rust-lang/rust/wiki/Teaching-Rust

**Talks:**
- http://mirror.linux.org.au/pub/linux.conf.au/2014/Friday/107-The_Rust_language_memory_ownership_and_lifetimes_-_Nicholas_Matsakis.mp4
- https://air.mozilla.org/guaranteeing-memory-safety-in-rust/
- https://pay.reddit.com/r/rust/comments/1x2nmq/yehuda_katz_rust_presentation_slides_from_pdx/
- http://www.infoq.com/presentations/Rust

**Guides:**
- https://github.com/rust-lang/rust/wiki/Rust-for-CXX-programmers

**Other:**
- https://github.com/rust-lang/rust/wiki/Docs

**Comment by crackofdusk** [comment]
The reference is useful for fact checking: http://doc.rust-lang.org/reference.html
